/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.TituloPropiedad;

/**
 *
 * @author escribano
 */
public class PropiedadPanel extends javax.swing.JPanel {
    TituloPropiedad propiedad;

    /**
     * Creates new form PropiedadPanel
     */
    public PropiedadPanel() {
        initComponents();
    }
    
    void setPropiedad(TituloPropiedad p){
        propiedad=p;
        field_nombre.setText(propiedad.getNombre());
        field_numCasas.setText(Integer.toString(propiedad.getNumCasas()));
        field_numHoteles.setText(Integer.toString(propiedad.getNumHoteles()));
        field_hipotecada.setText(Boolean.toString(propiedad.getHipotecado()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numCasas = new javax.swing.JLabel();
        numHoteles = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        hipotecada = new javax.swing.JLabel();
        field_nombre = new javax.swing.JTextField();
        field_numHoteles = new javax.swing.JTextField();
        field_hipotecada = new javax.swing.JTextField();
        field_numCasas = new javax.swing.JTextField();

        numCasas.setText("Casas");
        numCasas.setEnabled(false);

        numHoteles.setText("Hoteles");
        numHoteles.setEnabled(false);

        nombre.setText("Nombre");
        nombre.setEnabled(false);

        hipotecada.setText("¿Hipotecada?");
        hipotecada.setEnabled(false);

        field_nombre.setText("jTextField1");
        field_nombre.setEnabled(false);
        field_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_nombreActionPerformed(evt);
            }
        });

        field_numHoteles.setText("jTextField1");
        field_numHoteles.setEnabled(false);
        field_numHoteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_numHotelesActionPerformed(evt);
            }
        });

        field_hipotecada.setText("jTextField1");
        field_hipotecada.setEnabled(false);
        field_hipotecada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_hipotecadaActionPerformed(evt);
            }
        });

        field_numCasas.setText("jTextField1");
        field_numCasas.setEnabled(false);
        field_numCasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_numCasasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hipotecada, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numCasas, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(field_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_numHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_hipotecada, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_numCasas, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_nombre))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numCasas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_numCasas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_numHoteles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hipotecada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_hipotecada))
                .addGap(69, 69, 69))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void field_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_nombreActionPerformed

    private void field_numHotelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_numHotelesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_numHotelesActionPerformed

    private void field_hipotecadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_hipotecadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_hipotecadaActionPerformed

    private void field_numCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_numCasasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_numCasasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField field_hipotecada;
    private javax.swing.JTextField field_nombre;
    private javax.swing.JTextField field_numCasas;
    private javax.swing.JTextField field_numHoteles;
    private javax.swing.JLabel hipotecada;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel numCasas;
    private javax.swing.JLabel numHoteles;
    // End of variables declaration//GEN-END:variables
}
